### ISSUE TITLE
meta: Release 3.0.0

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/raven-csharp#246]
This issue will track the release of version 3.0.0

- [x] Background worker client: #242 
- [x] Bump up version of Newtonsoft.Json
- [ ] Make sure payload can be modified through `IRequester`

**Comment by bruno-garcia** [comment]
Since we've release  a new SDK, we currently have no plans to release a v3 of SharpRaven.
This might change in the future in which case a new task will be created.

The new Sentry .NET SDK is based on [Sentry's unified SDK](https://blog.sentry.io/2018/09/19/new-sdks-unified-python-javascript-dotnet-rust):

https://github.com/getsentry/sentry-dotnet/releases

https://www.nuget.org/packages/Sentry
